<#import "parts/common.ftlh" as c>

<@c.page>
    <h1 class="text-center"><b>BEATER</b></h1>
    <p style="font-size: x-large">BEATER is a social network for sharing ideas, discussions and community interaction. This platform gives users the opportunity to discuss various topics, communicate with like-minded people and share their knowledge from all over the world.</p>
    <p style="font-size: x-large">Welcome to us!</p>

</@c.page>